FROM debian:bookworm-slim
RUN \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y curl
ARG VERSION
ARG BASE_IMAGE=0ad-${VERSION}-x86_64.AppImage
RUN echo ${BASE_IMAGE}
RUN curl -LO https://github.com/0ad-matters/0ad-appimage/releases/download/v${VERSION}/${BASE_IMAGE}
RUN curl -LO https://github.com/0ad-matters/0ad-appimage/releases/download/v${VERSION}/${BASE_IMAGE}.sha1sum
RUN sha1sum -c ${BASE_IMAGE}.sha1sum
RUN chmod +x ${BASE_IMAGE}
RUN ./${BASE_IMAGE} --appimage-extract
WORKDIR /squashfs-root
RUN rm AppRun* 0ad.desktop 0ad.png
RUN rm -rf apprun-hooks
WORKDIR /squashfs-root/usr/data/mods
RUN rm -rf  _test* public mod
RUN chmod 777 -R /squashfs-root

FROM debian:bookworm-slim
RUN apt-get update
RUN apt-get upgrade -y
RUN apt install -y \
  libasound2 \
  libdrm2 \
  libgbm1 \
  libfreetype6 \
  libwayland-client0 \
  libx11-6 \
  libx11-xcb1 \
  zip \
  && rm -rf /var/lib/apt/lists

RUN useradd -M -U user0ad
RUN passwd -d user0ad
WORKDIR /home/user0ad
RUN chown user0ad:user0ad /home/user0ad
USER user0ad
COPY --from=0  /squashfs-root ./
